config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'search', to: 'pages#search'

  resources :interactions, only: :create

   root 'pages#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interaction.rb
class Interaction < ApplicationRecord
	 belongs_to :user_one, class_name: 'User' 
    belongs_to :user_two, class_name: 'User'

    

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  		devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :interactions_one, class_name: "Interaction", foreign_key: :user_one_id, dependent: :destroy

		has_many :interactions_two, class_name: "Interaction", foreign_key: :user_two_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:age, :gender])
 end
end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController

	def create
		Interaction.create!(user_one_id: current_user.id,
                        user_two_id: params[:id_user],
                        like: params[:me_gusta])
		
		redirect_to search_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
  end

  def search
  	@user = User.where.not(id: current_user.id).sample

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinderazo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
  	<div class="container">
	<p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
 
	<%= render 'shared/navbar' %>
    <%= yield %>


  	</div>

  	

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
	<h1>Home..!</h1>
<p>Find me in app/views/pages/home.html.erb</p>

	
	
</div>

app/views/pages/search.html.erb
<h1>Busqueda al azar </h1>


<div style="width: 15%; height: 270px; margin: auto; position: relative; margin-top: 50px; border: solid 1px ">
<%= @user.gender %>
<%= @user.email %> <br>
<%= @user.age %> <br>

<%= link_to 'like', interactions_path(id_user: @user.id, me_gusta: true), method: :post %>

<%= link_to 'Dislike', interactions_path(id_user: @user.id, me_gusta: false), method: :post %>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Mi App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.email, '#', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>